### ISSUE TITLE
Use tab-separator for scan?

### ISSUE THREAD

**Issue by florianduclot** [varemo/piano#1]
https://github.com/varemo/piano/blob/76373cf18b631e57b5eb2f5f2612b3ee4b1534c2/R/loadGSC.R#L107

As .gmt files are tab-delimited, shouldn't this scan be using ```sep = "\t"```?

My .gmt file (http://download.baderlab.org/EM_Genesets/current_release/Mouse/symbol/Mouse_AllPathways_November_01_2017_symbol.gmt) was not parsed correctly by loadGSC(), but using ```sep = "\t"``` fixed it.

**Comment by varemo** [comment]
It has been working on other .gtm files that I have tested. But if it fails for the file you point that, that is certainly an issue! I will check this asap. Probably you are correct, regarding the `sep = "\t"`, just need to verify that it works for all .gmt files. Thanks for reporting!

**Comment by florianduclot** [comment]
Thanks for looking at it!

**Comment by varemo** [comment]
Haven't forgotten about this, but got swamped with other work. Will get back to this after the holidays. I guess (hope) it is not a show stopper for you at this point anyways...

**Comment by florianduclot** [comment]
No problem for me, I made the change locally and it has been working fine for me since!

Thanks!

**Comment by varemo** [comment]
Now fixed and included in all branches! Should propagate to Bioconductor within a few days. Thanks again for pointing this out.
